#version: '3'

  # djangoTemplate:
  #   container_name: djangotemplate
  #   user: root
  #   volumes:
  #     - djangotemplate:/var/lib/postgresql/
  #   networks:
  #   - microservices
  #   build: backend/djangotemplate
  #   image: djangotemplate
  #   expose :
  #   - "8080"
  #   restart: on-failure

networks:
  microservices:
    external: true

volumes:
  secret_volume:
  user:
  matchmaking:
  chat:
  game3d:
  pokemap:


services:
  nginx:
    container_name: nginx
    networks:
    - microservices
    build: services/nginx
    image: nginx
    ports:
      - "4430:4430"
    restart: on-failure

  user:
    container_name: user
    user: root
    volumes:
      - user:/var/lib/postgresql/
    networks:
    - microservices
    build: services/backend/user
    image: user
    expose :
    - "4430"
    restart: on-failure

  token:
    container_name: jwtoken
    networks:
      - microservices
    build: services/backend/JWToken
    image: jwtoken
    expose :
      - "4430"
    restart: on-failure

  game3d:
    container_name: game3d
    user: root
    volumes:
    - game3d:/var/lib/postgresql
    networks:
      - microservices
    build: services/backend/game3d
    image: game3d
    expose :
      - "4430"
    restart: on-failure

  matchmaking:
    container_name: matchmaking
    user: root
    volumes:
      - matchmaking:/var/lib/postgresql/
    networks:
    - microservices
    build: services/backend/matchmaking
    image: matchmaking
    expose :
    - "4430"
    restart: on-failure

  pokemap:
    container_name: pokemap
    networks:
      - microservices
    build: services/backend/pokemap
    image: pokemap
    expose :
      - "4430"
    restart: on-failure

  chat:
    container_name: chat
    user: root
    volumes:
      - chat:/var/lib/postgresql/
    networks:
    - microservices
    build: services/backend/chat
    image: chat
    expose :
    - "4430"
    restart: on-failure
