version: '3'

networks:
  microservices:
    driver: bridge

services:
  nginx:
    container_name: nginx
    networks:
    - microservices
    build: nginx
    image: nginx
    ports:
      - "8080:80"
    restart: on-failure

  user:
    container_name: user
    networks:
    - microservices
    build: backend/user
    image: user
    expose :
    - "8080"
    restart: on-failure

  token:
    container_name: token
    networks: 
      - microservices
    build: backend/token
    image: token
    expose :
      - "5435"
    restart: on-failure
